name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: build-htz-01
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release
        id: semantic
        uses: https://git.jdbnet.co.uk/jamie/go-semantic-release-provider-gitea@v1.2.3
        with:
          gitea-host: ${{ gitea.server_url }}
          gitea-token: ${{ secrets.GITEA_TOKEN }}

      - name: Build and push Docker image
        if: steps.semantic.outputs.version != ''
        run: |
          VERSION="v${{ steps.semantic.outputs.version }}"
          IMAGE="cr.jdbnet.co.uk/public/ipam"
          docker build -t $IMAGE:$VERSION -t $IMAGE:latest -t $IMAGE:v2 --build-arg VERSION=$VERSION .
          docker push $IMAGE:$VERSION && docker push $IMAGE:latest && docker push $IMAGE:v2